/*
 * UI.java
 *
 * Created on __DATE__, __TIME__
 */

package UserInterface;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import Data.Data;
import Data.BulidPoint;
import Data.KNN;
import Data.SortByDistance;

/**
 *
 * @author  __USER__
 */
public class UI extends javax.swing.JFrame {

	/** Creates new form UI */
	public UI() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		Button10 = new javax.swing.JButton();
		Button20 = new javax.swing.JButton();
		Button30 = new javax.swing.JButton();
		Button40 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jPanel1MouseClicked(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 431,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 240,
				Short.MAX_VALUE));

		jButton1.setText("\u751f\u6210\u968f\u673a\u70b9");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		Button10.setText("10");
		Button10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button10ActionPerformed(evt);
			}
		});

		Button20.setText("20");
		Button20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button20ActionPerformed(evt);
			}
		});

		Button30.setText("30");
		Button30.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button30ActionPerformed(evt);
			}
		});

		Button40.setText("40");
		Button40.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button40ActionPerformed(evt);
			}
		});

		jButton2.setText("\u67e5\u770b\u6392\u5e8f\u7ed3\u679c");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				10,
																				10,
																				10)
																		.add(
																				jButton1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				Button10)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				Button20)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				Button30)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				Button40)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jButton2))
														.add(
																jPanel1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton1).add(
																Button10).add(
																Button20).add(
																Button30).add(
																Button40).add(
																jButton2))
										.addContainerGap(35, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void Button40ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		knnaction(40);
	}

	private void Button30ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		knnaction(30);
	}

	private void Button20ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		knnaction(20);
	}

	private void Button10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		knnaction(10);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Collections.sort(data, new SortByDistance());
		for (int i = 0; i < data.size(); i++) {
			System.out.println(data.get(i).getDistance());
		}
	}

	private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if (!clicked) {
			thePoint = new Point(evt.getX(), evt.getY());
			drawMidStar();
			test = new Data(thePoint, Color.BLACK, thePoint);
			clicked = true;
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		drawMidStar();
		Graphics g = jPanel1.getGraphics();
		data = new ArrayList<Data>();
		data = BulidPoint.generatePoint(thePoint);
		for (int i = 0; i < 50; i++) {
			g.setColor(data.get(i).getColor());
			g
					.drawOval(data.get(i).getPoint().x,
							data.get(i).getPoint().y, 1, 1);
			System.out.println(data.get(i).getDistance() + "+"
					+ data.get(i).getPoint());
		}
	}

	private void drawMidStar() {
		Graphics g = jPanel1.getGraphics();
		g.setColor(Color.BLACK);
		g.drawOval(thePoint.x, thePoint.y, 5, 5);

	}

	private void knnaction(int k) {
		knn = new KNN();
		String sh = knn.knn(data, test, k);
		Graphics g = jPanel1.getGraphics();
		for (int i = 0; i < knn.out.size(); i++) {
			Data d = knn.out.get(i);
			System.out.println(d.getPoint());
			g.drawLine(d.getPoint().x, d.getPoint().y, thePoint.x, thePoint.y);
		}
		JOptionPane.showMessageDialog(null, sh, "KNN",
				JOptionPane.PLAIN_MESSAGE);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

	    try
	    {
	    	UIManager
			.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
	    }
	    catch(Exception e)
	    {
	        //TODO exception
	    }
		java.awt.EventQueue.invokeLater(new Runnable() {
			
			public void run() {
				new UI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Button10;
	private javax.swing.JButton Button20;
	private javax.swing.JButton Button30;
	private javax.swing.JButton Button40;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

	private ArrayList<Data> data;
	private boolean clicked = false;
	private Point thePoint;
	private Data test;
	private KNN knn;
}